-- WITH
-- RANKED AS (
--     SELECT
--         ID,
--         ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKING,
--         (SELECT COUNT(*) FROM ECOLI_DATA) AS TOTAL_COUNT
--     FROM ECOLI_DATA
-- ),
-- CLASSIFIED AS (
--     SELECT
--         ID,
--         CASE
--             WHEN RANKING <= TOTAL_COUNT * 0.25 THEN 'CRITICAL'
--             WHEN RANKING <= TOTAL_COUNT * 0.5 THEN 'HIGH'
--             WHEN RANKING <= TOTAL_COUNT * 0.75 THEN 'MEDIUM'
--             ELSE 'LOW'
--         END AS COLONY_NAME
--     FROM RANKED
-- )
-- SELECT *
-- FROM CLASSIFIED
-- ORDER BY ID;

WITH 
TOTAL_COUNT AS (
    SELECT COUNT(*) AS TOTAL FROM ECOLI_DATA
),
RANKED AS (
    SELECT
        ID,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN
    FROM ECOLI_DATA
),
CLASSIFIED AS (
    SELECT
        R.ID,
        CASE
            WHEN RN <= FLOOR(T.TOTAL * 0.25) THEN 'CRITICAL'
            WHEN RN <= FLOOR(T.TOTAL * 0.50) THEN 'HIGH'
            WHEN RN <= FLOOR(T.TOTAL * 0.75) THEN 'MEDIUM'
            ELSE 'LOW'
        END AS COLONY_NAME
    FROM RANKED R
    JOIN TOTAL_COUNT T
)
SELECT ID, COLONY_NAME
FROM CLASSIFIED
ORDER BY ID;