SELECT GRAND_CHILD.ID
FROM ECOLI_DATA AS GRAND_CHILD
JOIN ECOLI_DATA AS CHILD
    ON GRAND_CHILD.PARENT_ID = CHILD.ID
JOIN ECOLI_DATA AS PARENT
    ON CHILD.PARENT_ID = PARENT.ID
WHERE PARENT.PARENT_ID IS NULL
ORDER BY GRAND_CHILD.ID;