WITH
RANKING AS (
    SELECT
        FLAVOR,
        FH.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL_ORDER,
        ROW_NUMBER() OVER(ORDER BY FH.TOTAL_ORDER + J.TOTAL_ORDER DESC) AS RN
    FROM FIRST_HALF FH
    JOIN (
        SELECT
            FLAVOR,
            SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
        ) J USING (FLAVOR)
)
SELECT FLAVOR
FROM RANKING
WHERE RN <= 3;