SELECT TB1.CATEGORY, TB2.MAX_PRICE, TB1.PRODUCT_NAME
FROM
FOOD_PRODUCT AS TB1
    INNER JOIN (
        SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY REGEXP '과자|국|김치|식용유'
        GROUP BY CATEGORY
    ) AS TB2
    ON TB1.CATEGORY = TB2.CATEGORY
    AND TB1.PRICE = TB2.MAX_PRICE
ORDER BY PRICE DESC;