WITH
SCORES AS (
    SELECT
        E.EMP_NO,
        AVG(G.SCORE) AS SCORE
    FROM HR_EMPLOYEES E
        JOIN HR_GRADE G USING(EMP_NO)
    GROUP BY EMP_NO
)
SELECT
    E.EMP_NO, E.EMP_NAME,
    CASE
        WHEN S.SCORE >= 96 THEN 'S'
        WHEN S.SCORE >= 90 THEN 'A'
        WHEN S.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN S.SCORE >= 96 THEN E.SAL * 0.2
        WHEN S.SCORE >= 90 THEN E.SAL * 0.15
        WHEN S.SCORE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM SCORES S
    JOIN HR_EMPLOYEES E USING(EMP_NO);