SELECT
    HOUR(DATETIME) AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)
    IN (
        SELECT HOUR(DATETIME) AS HOUR
        FROM ANIMAL_OUTS
        WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
    )
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);