WITH
RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)
SELECT
    HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
    RIGHT JOIN HOURS H ON HOUR(A.DATETIME) = H.HOUR
GROUP BY HOUR
ORDER BY HOUR;