WITH
SCORES AS (
    SELECT
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT
    S.SCORE,
    E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
    JOIN SCORES S USING(EMP_NO)
ORDER BY S.SCORE DESC LIMIT 1;


WITH
RANKINGS AS (
    SELECT
        E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL,
        SUM(G.SCORE) AS SCORE,
        RANK() OVER (ORDER BY SUM(G.SCORE) DESC) AS RANKING
    FROM HR_EMPLOYEES E
        JOIN HR_GRADE G USING(EMP_NO)
    WHERE G.YEAR = 2022
    GROUP BY EMP_NO
)
SELECT
    SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM RANKINGS
WHERE RANKING = 1;