SELECT
    ANIMAL_ID,
    NAME
FROM ANIMAL_INS I
    LEFT OUTER JOIN ANIMAL_OUTS O
        USING(ANIMAL_ID, ANIMAL_TYPE, NAME)
WHERE O.DATETIME IS NOT NULL
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;